/* GENERATED by scripts/capture.mjs. Do not edit: run `npm run capture`.
 *
 * Every number here came back from https://rulestack.thecompound.tech/api/score, reached by the real stubless binary
 * at packages/stubless/bin/stubless.mjs. Nothing in this file was typed by hand and nothing
 * in it was scored anywhere but RuleStack.
 */

export const RUN = {
 "scoredAt": "2026-09-24T13:19:03.052Z",
 "api": "https://rulestack.thecompound.tech",
 "endpoint": "POST /api/score",
 "recogniserReadAt": "2026-09-04",
 "recogniserSource": "ghscrape MATCHERS",
 "limits": {
  "maxFiles": 60,
  "maxFileChars": 1000000,
  "maxTotalChars": 2000000
 },
 "formats": [
  {
   "kind": "agents_md",
   "format": "agents-md",
   "name": "AGENTS.md",
   "filename": "AGENTS.md"
  },
  {
   "kind": "claude_md",
   "format": "claude-md",
   "name": "CLAUDE.md",
   "filename": "CLAUDE.md"
  },
  {
   "kind": "gemini_md",
   "format": "gemini-md",
   "name": "GEMINI.md",
   "filename": "GEMINI.md"
  },
  {
   "kind": "cursor_rule",
   "format": "cursor-rules",
   "name": "Cursor rules",
   "filename": ".cursor/rules/*.mdc"
  },
  {
   "kind": "cursorrules",
   "format": "cursorrules",
   "name": ".cursorrules",
   "filename": ".cursorrules"
  },
  {
   "kind": "copilot_instructions",
   "format": "copilot-instructions",
   "name": "Copilot instructions",
   "filename": ".github/copilot-instructions.md"
  },
  {
   "kind": "windsurf_rules",
   "format": "windsurf-rules",
   "name": "Windsurf rules",
   "filename": ".windsurf/rules/*.md"
  },
  {
   "kind": "cline_rules",
   "format": "cline-rules",
   "name": "Cline rules",
   "filename": ".clinerules"
  }
 ],
 "summaryRepo": "kyisaiah47/leakless",
 "repos": [
  {
   "repo": "kyisaiah47/blockdex",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/breachprobe",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/citerank",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/kitgrade",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/listrun",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/matchline",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/policydrift",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/rulestack",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/scriptprobe",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/shipwall",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/skillworks",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/stacktab",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/stillshipping",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/storeready",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/tooldrift",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/toolproof",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/wirecall",
   "set": "dev",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/glanceless",
   "set": "package",
   "exit": 1,
   "files": []
  },
  {
   "repo": "kyisaiah47/leakless",
   "set": "package",
   "exit": 0,
   "files": [
    {
     "path": "AGENTS.md",
     "format": "agents-md",
     "formatName": "AGENTS.md",
     "quality": 99,
     "rawPoints": 99,
     "cappedAt100": false,
     "words": 515,
     "headings": 8,
     "commands": 5,
     "codeBlocks": 2,
     "tags": [
      "build",
      "test",
      "lint-format",
      "code-style",
      "architecture",
      "do-not"
     ],
     "capabilities": [
      {
       "key": "length",
       "label": "Length",
       "points": 34,
       "max": 34,
       "detail": "515 words, the band this scorer rates highest"
      },
      {
       "key": "structure",
       "label": "Section headings",
       "points": 14,
       "max": 14,
       "detail": "8 headings"
      },
      {
       "key": "commands",
       "label": "Runnable commands",
       "points": 15,
       "max": 20,
       "detail": "5 commands an agent can execute"
      },
      {
       "key": "coverage",
       "label": "Core topic coverage",
       "points": 15,
       "max": 15,
       "detail": "5 of 5: build, test, lint-format, code-style, architecture"
      },
      {
       "key": "prohibitions",
       "label": "Explicit prohibitions",
       "points": 7,
       "max": 7,
       "detail": "the file tells the agent what never to do"
      },
      {
       "key": "specificity",
       "label": "Names this repository's own paths",
       "points": 8,
       "max": 8,
       "detail": "the file names real directories in this repository"
      },
      {
       "key": "examples",
       "label": "Worked examples",
       "points": 6,
       "max": 6,
       "detail": "2 fenced code blocks"
      }
     ],
     "reasons": []
    }
   ]
  },
  {
   "repo": "kyisaiah47/stubless",
   "set": "package",
   "exit": 0,
   "files": [
    {
     "path": "AGENTS.md",
     "format": "agents-md",
     "formatName": "AGENTS.md",
     "quality": 100,
     "rawPoints": 104,
     "cappedAt100": true,
     "words": 552,
     "headings": 8,
     "commands": 7,
     "codeBlocks": 2,
     "tags": [
      "build",
      "test",
      "lint-format",
      "code-style",
      "architecture",
      "testing-strategy",
      "do-not"
     ],
     "capabilities": [
      {
       "key": "length",
       "label": "Length",
       "points": 34,
       "max": 34,
       "detail": "552 words, the band this scorer rates highest"
      },
      {
       "key": "structure",
       "label": "Section headings",
       "points": 14,
       "max": 14,
       "detail": "8 headings"
      },
      {
       "key": "commands",
       "label": "Runnable commands",
       "points": 20,
       "max": 20,
       "detail": "7 commands an agent can execute"
      },
      {
       "key": "coverage",
       "label": "Core topic coverage",
       "points": 15,
       "max": 15,
       "detail": "5 of 5: build, test, lint-format, code-style, architecture"
      },
      {
       "key": "prohibitions",
       "label": "Explicit prohibitions",
       "points": 7,
       "max": 7,
       "detail": "the file tells the agent what never to do"
      },
      {
       "key": "specificity",
       "label": "Names this repository's own paths",
       "points": 8,
       "max": 8,
       "detail": "the file names real directories in this repository"
      },
      {
       "key": "examples",
       "label": "Worked examples",
       "points": 6,
       "max": 6,
       "detail": "2 fenced code blocks"
      }
     ],
     "reasons": []
    }
   ]
  }
 ]
} as const;

/** The job summary the gate printed for kyisaiah47/leakless, byte for byte. */
export const SUMMARY = "## stubless\n\n1 agent instruction file scored by [RuleStack](https://rulestack.thecompound.tech). The repository score is the strongest file, which is what RuleStack's own badge reports: **99/100**, at or above the threshold of 60.\n\n| File | Format | Score | Words | Headings | Commands | Topics |\n| --- | --- | --: | --: | --: | --: | --: |\n| `AGENTS.md` | AGENTS.md | 99/100 | 515 | 8 | 5 | 6 |\n\n### Where `AGENTS.md` earned its points\n\n| Capability | Points | Measured |\n| --- | --: | --- |\n| Length | 34/34 | 515 words, the band this scorer rates highest |\n| Section headings | 14/14 | 8 headings |\n| Runnable commands | 15/20 | 5 commands an agent can execute |\n| Core topic coverage | 15/15 | 5 of 5: build, test, lint-format, code-style, architecture |\n| Explicit prohibitions | 7/7 | the file tells the agent what never to do |\n| Names this repository's own paths | 8/8 | the file names real directories in this repository |\n| Worked examples | 6/6 | 2 fenced code blocks |\n\n### Badge\n\n```markdown\n[![AGENTS.md](https://toolproof.thecompound.tech/badge/rulestack/kyisaiah47/leakless.svg)](https://rulestack.thecompound.tech)\n```\n\nThat badge reads the RuleStack nightly index, not this run. Until the nightly crawl reaches a repository it renders **not indexed**, which is the correct output for an unmeasured subject and is not a bad score.\n\n<sub>Scored with the same classifier RuleStack runs over [real repositories](https://rulestack.thecompound.tech/configs) every night. stubless is built and used in production by [Compound Labs](https://thecompound.tech).</sub>\noutput score=99\noutput best-file=AGENTS.md\noutput files=1\noutput report-path=/var/folders/nw/lpnmm4l56mx1mfmhgt7ps1jr0000gn/T/stubless-jTCCs5/stubless-report.json\noutput badge=[![AGENTS.md](https://toolproof.thecompound.tech/badge/rulestack/kyisaiah47/leakless.svg)](https://rulestack.thecompound.tech)\nstubless: 1 file(s), best AGENTS.md at 99/100, threshold 60";
