'use client';
import { useState } from 'react';
import NumberFlow from '@number-flow/react';
import { Icon } from './Icon';
import { EXITS, PRODUCT, SOURCES } from '@/lib/product';
import FAMILY from '@/lib/app-family.json';

const thresholds = [60, 70, 80];
const files = [['AGENTS.md', 90, 'agents-md', 'Recognised'], ['CLAUDE.md', 0, 'claude-md', 'Not present'], ['.cursor/rules/*.mdc', 0, 'cursor-rules', 'Not present'], ['.github/copilot-instructions.md', 0, 'copilot', 'Not present']];

export default function Console() {
  const [threshold, setThreshold] = useState(60); const [strip, setStrip] = useState(false); const pass = threshold <= 60;
  return <>
    <div className="source-line">STUBLESS READS THE PACKAGE, THEN RULESTACK READS THE FILES. PACKAGE VERSION {PRODUCT.version}. SOURCE REGISTER {SOURCES.length} CLAIMS.</div>
    <header className="masthead"><a className="brand" href={PRODUCT.repo}><img className="mk" src="/icon.svg" alt="" width={20} height={20} /><span>{PRODUCT.name}</span></a><button className="app-switch" aria-expanded={strip} onClick={() => setStrip(!strip)}><Icon name="caret-up-down" size={13} /></button><span className="standing">GITHUB ACTION, RULESTACK SCORE GATE</span><nav><a className="active" href="#console"><Icon name="terminal-window" /> Console</a><a href={PRODUCT.repo}><Icon name="github-logo" /> Repository</a><a href="#method"><Icon name="file-text" /> Method</a></nav><span className="live"><i /> PACKAGE READ 23 SEPT 2026</span><a className="action" href={`${PRODUCT.repo}#usage`}><Icon name="arrow-square-out" /> Read usage</a></header>
    {strip && <div className="app-strip"><span>COMPOUND LABS / {FAMILY.label.toUpperCase()}</span>{FAMILY.apps.map((a) => <a key={a.slug} href={a.url} className={a.slug === PRODUCT.slug + '-site' ? 'selected' : undefined}><img src={a.logo} alt="" width={14} height={14} />{a.name}</a>)}</div>}
    <div className="folio" aria-label="Folio scrolls horizontally"><span><NumberFlow value={2} /> recognised files</span><span><NumberFlow value={SOURCES.length} /> claims sourced</span><span><NumberFlow value={90} /> strongest score</span><span><NumberFlow value={threshold} /> default threshold</span><span>0 runtime dependencies</span><span>SCROLL FOR MORE</span></div>
    <section className="head-band" id="console"><div><p className="eyebrow">THE JOB THAT FAILS</p><h1>Score a repository's agent instructions, then fail below {threshold}.</h1><p className="lede">{PRODUCT.lede}</p></div><div className="facts"><div><span>PACKAGE</span><b>stubless {PRODUCT.version}</b></div><div><span>RUNTIME</span><b>Node.js ≥ 18</b></div><div><span>LICENSE</span><b>MIT</b></div><div><span>REPOSITORY</span><b>kyisaiah47/stubless</b></div></div></section>
    <section className="control-bar"><div className="control-row"><span className="gutter">THRESHOLD</span>{thresholds.map((value) => <button key={value} className={threshold === value ? 'chip pressed' : 'chip'} onClick={() => setThreshold(value)}><Icon name="gauge" size={14} /> {value} <small>fail below</small></button>)}</div><div className="control-note"><Icon name="lightning" /> Change the threshold. Re-read the score summary, exit state and rows.</div></section>
    <div className="frame"><aside className="rail rail-left"><RailHeading icon="file-text" text="FILES IN THE WALK" />{files.map(([name, score, kind, state]) => <div className="file-row" key={name}><Icon name={state === 'Recognised' ? 'check' : 'file-dashed'} /><span>{name}<small>{kind}</small></span><b>{state === 'Recognised' ? <NumberFlow value={Number(score)} /> : '·'}</b></div>)}<RailHeading icon="list-numbers" text="EXIT CODES" />{EXITS.map((item) => <div className="exit-mini" key={item.code}><span className={`dot ${item.ink}`} /><b>{item.code}</b><span>{item.label}</span></div>)}</aside>
      <main className="track"><section className="band"><SectionHead eyebrow="ASSERTED" title="What the package says this job checks" time="READ 23 SEPT 2026" /><p className="band-copy">A stub agent config parses and teaches nothing. stubless gives that prose a linter by asking RuleStack to score the repository files it recognises.</p><div className="table-wrap"><table><thead><tr><th>INPUT</th><th>DEFAULT</th><th>MEANING</th><th>READ FROM</th></tr></thead><tbody><tr><td>threshold</td><td>60</td><td>Fail below this score.</td><td>action.yml</td></tr><tr><td>per-file-threshold</td><td>unset</td><td>Every recognised file clears it.</td><td>README.md</td></tr><tr><td>workspace</td><td>checkout root</td><td>Directory to walk.</td><td>README.md</td></tr><tr><td>timeout</td><td>60 seconds</td><td>Request deadline before exit 2.</td><td>README.md</td></tr></tbody></table><span className="scroll-note">SCROLL FOR MORE</span></div></section>
      <section className="band"><SectionHead eyebrow="EXAMPLE OUTPUT" title="The README example shows a 90 point file" time="READ 23 SEPT 2026" /><div className="score-line"><div><strong><NumberFlow value={90} /></strong><span>/ 100 README example score</span></div><div className="meter"><i style={{ width: '90%' }} /></div><span className={`status ${pass ? 'pass' : 'fail'}`}>{pass ? 'PASS' : 'FAIL'} AT {threshold}</span></div><div className="table-wrap"><table><thead><tr><th>FILE</th><th>FORMAT</th><th>SCORE</th><th>STATE</th></tr></thead><tbody><tr><td><Icon name="file-text" /> AGENTS.md</td><td>AGENTS.md</td><td><NumberFlow value={90} /> / 100</td><td className="good">clears {threshold}</td></tr><tr><td><Icon name="file-text" /> CLAUDE.md</td><td>CLAUDE.md</td><td>not present in package</td><td>not scored</td></tr></tbody></table><span className="scroll-note">SCROLL FOR MORE</span></div></section>
      <section className="band" id="method"><SectionHead eyebrow="THE BOUNDARY" title="RuleStack owns the recogniser" time="LIVE API, NOT A COPY" /><div className="boundary-grid"><div><Icon name="broadcast" size={20} /><p>The recogniser lives in RuleStack. stubless reads its formats from <code>GET /api/score</code> on every run.</p></div><div><Icon name="prohibit" size={20} /><p>A failed fetch, an unreadable file, or an unparseable threshold becomes exit 2. It never collapses into a pass.</p></div><div><Icon name="seal-check" size={20} /><p>The score is the strongest recognised file, the same number RuleStack's badge reports.</p></div></div></section>
      <section className="band source-band"><SectionHead eyebrow="SOURCE REGISTER" title="Every claim on this page has a line to read" time={`${SOURCES.length} ROWS`} /><div className="source-list">{SOURCES.slice(0, 8).map((source) => <a href={source.url} key={source.id}><span>{source.cite}</span><q>{source.quote}</q><small>{source.read_at}</small></a>)}</div></section></main>
      <aside className="rail rail-right"><RailHeading icon="clock" text="THE RUN" /><div className="run-row"><span>PACKAGE</span><b>0.1.0</b></div><div className="run-row"><span>RECOGNISER</span><b>RuleStack API</b></div><div className="run-row"><span>DEPENDENCIES</span><b>0</b></div><div className="run-row"><span>NODE</span><b>≥ 18</b></div><RailHeading icon="warning-circle" text="THREE STATES" />{EXITS.map((item) => <div className="state-row" key={item.code}><span className={`state-mark ${item.ink}`}>{item.code}</span><p><b>{item.label}</b>{item.text}</p></div>)}<RailHeading icon="arrow-square-out" text="WHERE THIS WAS READ" /><a className="rail-link" href={PRODUCT.repo}>github.com/kyisaiah47/stubless</a><a className="rail-link" href="https://rulestack.thecompound.tech">rulestack.thecompound.tech</a></aside></div>
    <footer><div><span>Built by</span><img className="studio-credit-mark" src="/brand/compound-labs.svg" alt="Compound Labs" width={20} height={20} /></div><span>© 2026 stubless. A Compound Labs product.</span><a href="mailto:hello@thecompound.tech">hello@thecompound.tech</a></footer>
  </>;
}
function SectionHead({ eyebrow, title, time }: { eyebrow: string; title: string; time: string }) { return <div className="section-head"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><time>{time}</time></div>; }
function RailHeading({ icon, text }: { icon: 'file-text' | 'list-numbers' | 'clock' | 'warning-circle' | 'warning-octagon' | 'arrow-square-out'; text: string }) { return <h3 className="rail-heading"><Icon name={icon} size={14} /> {text}</h3>; }
