#!/usr/bin/env node
/* Vendors the Phosphor Regular glyphs THIS app draws, from the Phosphor core repo.
 *
 *   npm run icons
 *
 * From the source, never from another product's tree. The estate has no shared component
 * library to take one from: those repos were purged on 2026-09-14 and every app vendors its own,
 * so a copy of a copy would have no source left to re-read.
 *
 * The glyphs compile into src/lib/phosphor.ts as path bodies in currentColor, so a glyph takes
 * the ink of whatever sits beside it. No icon font, no runtime CDN.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'vendor/phosphor');
const BASE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/assets/regular';
const LICENSE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/LICENSE';

/* One glyph per caller. A glyph nothing draws is a glyph to delete rather than to keep in case,
 * and the register gate counts the callers. */
const WANT = [
  'file-text',          // a recognised instruction file, in a row and in the format rail
  'file-dashed',        // a repository the recogniser matched nothing in
  'gauge',              // the score column and the threshold panel
  'ruler',              // the threshold control gutter
  'funnel-simple',      // the format control gutter
  'seal-check',         // at or above the threshold
  'warning-octagon',    // below the threshold
  'question',           // could not check, which is exit 2
  'terminal-window',    // the captured job summary
  'github-logo',        // a repository this was read out of
  'list-checks',        // the capability bands
  'prohibit',           // the three things that do not exist in the action
  'caret-up-down',      // the app switch beside the mark
  'caret-right',        // a row that opens
  'arrow-square-out',   // an outward link
  'clock',              // a read date
  'hash',               // the exit code table
  'broadcast',          // RuleStack, read live on every run
  'text-align-left',    // the words metric
  'brackets-curly',     // the commands metric
  'tag',                // the section tags metric
  'copy',               // copy the workflow
];

await mkdir(OUT, { recursive: true });
const index = {};
for (const name of WANT) {
  const url = `${BASE}/${name}.svg`;
  const r = await fetch(url);
  if (!r.ok) throw new Error(`HTTP ${r.status} on ${url}`);
  const svg = await r.text();
  const body = svg
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/fill="#[0-9a-fA-F]{3,8}"/g, 'fill="currentColor"')
    .trim();
  await writeFile(resolve(OUT, `${name}.svg`), svg);
  index[name] = body;
  process.stdout.write(`${name}  ${svg.length}b\n`);
}
const lic = await fetch(LICENSE);
if (!lic.ok) throw new Error(`HTTP ${lic.status} on the licence`);
await writeFile(resolve(OUT, 'LICENSE'), await lic.text());

await writeFile(
  resolve(ROOT, 'src/lib/phosphor.ts'),
  `// GENERATED by scripts/icons.mjs from ${BASE}\n` +
    `// Phosphor Icons, MIT. The licence is vendored at vendor/phosphor/LICENSE.\n` +
    `export const GLYPH: Record<string, string> = ${JSON.stringify(index, null, 1)};\n`,
);
process.stdout.write(`\nwrote src/lib/phosphor.ts, ${WANT.length} glyphs\n`);
